INSERT INTO MEMBER (MEMBER_ID, EMAIL, NAME, PASSWORD) VALUES (1, 'admin@javabom.com', 'admin', '$2a$10$GlDibkYYON5WmjIqXJCV2.hmHBoCf//vggYLaTS/eHLF1qs8flL2u');
INSERT INTO MEMBER_ROLE (SEQ, MEMBER_ID, ROLE) VALUES (1, 1, 'ADMIN');
